spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://37.77.104.67:5432/course
    username: postgres
    password: 123456

  flyway:
    url: jdbc:postgresql://37.77.104.67:5432/course
    user: postgres
    password: 123456
    enabled: true
    #locations: classpath:db/migration
    locations:
      - 'classpath:db/migration'
